RepositoryDemo/Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using RepositoryDemo.Services.Abstract;

namespace RepositoryDemo.Controllers;

public class BasketController : Controller
{
    private readonly IBasketService _basketService;

    // GET
    public BasketController(IBasketService basketService)
    {
        _basketService = basketService;
    }

    
    //Get
    public async Task<IActionResult> Index()
    {
        if (!User.Identity.IsAuthenticated) return RedirectToAction("Login", "Account");
        var result = await _basketService.BasketIndex();
        
        ViewBag.BasketTotalPrice = result.Data.ProductTotalPrice;
        
        return View(result.Data.Products);
    }
    
    
    // Add
    public async Task<IActionResult> AddBasket([FromForm] int id, int addProductCount)
    {
        var result = await _basketService.AddBasket(id, addProductCount);

        if (result.Success) return RedirectToAction("Index");

        return View("Index");
    }


    
    //Plus
    public async Task<IActionResult> ProductCountPlus([FromForm] int id)
    {
        var result = _basketService.ProductCountPlus(id);
        
        return Ok(result);
    }
    
    

    //Minus
    public async Task<IActionResult> ProductCountMinus([FromForm] int id)
    {
        var result = _basketService.ProductCountMinus(id);
        
        return Ok(result);
    }


    //Remove
    public async Task<IActionResult> RemoveProduct(int id)
    {
        var result = _basketService.RemoveProduct(id);

        return Ok(result);
    }








}

RepositoryDemo/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using RepositoryDemo.Dtos;
using RepositoryDemo.Services.Abstract;

namespace RepositoryDemo.Controllers;

public class CategoryController : Controller
{
    private readonly ICategoryService _categoryService;

    // GET
    public CategoryController(ICategoryService categoryService)
    {
        _categoryService = categoryService;
    }

    
    // Get All
    public async Task<IActionResult> Index()
    {
        var categories = await _categoryService.GetAll();
        return View(categories);
    }

    
    // Create Get
    public IActionResult Create()
    {
        return View();
    }


    //Create Post
    [HttpPost]
    public async Task<IActionResult> Create(CategoryCreateDto categoryCreateDto)
    {
        if (ModelState.IsValid)
        {
            var category = await _categoryService.Add(categoryCreateDto);
            return RedirectToAction("Index");
        }

        return View();
    }


    //Update Get
    [HttpGet]
    public async Task<IActionResult> Update()
    {
        return View();
    }


    //Update Post
    [HttpPost]
    public async Task<IActionResult> Update(CategoryUpdateDto categoryUpdateDto)
    {
        if (ModelState.IsValid)
        {
            await _categoryService.UpdateCategory(categoryUpdateDto);
            return RedirectToAction("Index");
        }

        return View();
    }


    //Delete
    public async Task<IActionResult> Delete(int id)
    {
        await _categoryService.Delete(id);
        return RedirectToAction("Index");
    }
}

RepositoryDemo/Controllers/OrderController.cs
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using RepositoryDemo.Services.Abstract;
using RepositoryDemo.ViewModels;

namespace RepositoryDemo.Controllers;

public class OrderController : Controller
{
    private readonly IOrderService _orderService;
        
    public OrderController(IOrderService orderService)
    {
        _orderService = orderService;
    }

    
    // GET All
    public async Task<IActionResult> Index()
    {
        var result = await _orderService.GetAll();
        return View(result.Data);
    }


    //Create
    [HttpPost]
    public async Task<IActionResult> Create([FromForm] List<int> productList)
    {
        var result = await _orderService.Add(productList);

        return RedirectToAction("Index");
    }


    //User Info Get
    public async Task<IActionResult> UserInfo(int productId)
    {
        ViewBag.productId = productId;
        return View();
    }


    //User Info Post
    [HttpPost]
    public async Task<IActionResult> UserInfo(CreateOrderByUserDto createOrderByUserDto, int productId)
    {
        var result = await _orderService.CreateOrderByUser(createOrderByUserDto, productId);
        
        (string message, bool success) msg;
        
        if (!result.Success)
        {
            // ModelState.AddModelError("errorMessage", result.Message);
            msg = Notify(result.Success, result.Message);

            return RedirectToAction("UserInfo", msg);
        }

        msg = Notify(result.Success, result.Message);


        return RedirectToAction("UserInfo", msg);
    }

    
    
    // Alert
    private (string message, bool success) Notify(bool success, string message)
    {
        var msg = new
        {
            Message = message,
            Success = success,
        };

        TempData["notification"] = JsonSerializer.Serialize(msg);

        return (msg.Message, msg.Success);
    }
    
    
    
    
}

RepositoryDemo/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RepositoryDemo.Dtos;
using RepositoryDemo.Services.Abstract;
using IResult= RepositoryDemo.Results.IResult;
namespace RepositoryDemo.Controllers;

public class ProductController : Controller
{
    private readonly ICategoryService _categoryService;
    private readonly IProductService _productService;

    public ProductController(IProductService productService, ICategoryService categoryService, IUserService userService)
    {
        _productService = productService;
        _categoryService = categoryService;
    }

    
    
    
    //Get All
    public async Task<IActionResult> Index()
    {
        var products = await _productService.GetAll();
        return View(products.Data);
    }


    
    
    //Details
    public async Task<IActionResult> Details(int id)
    {
        var product = await _productService.Details(id);
        return View(product.Data);
    }


    //Add Get
    public async Task<IActionResult> Add()
    {
        var categories = await _categoryService.GetAll();
        ViewData["categories"] = new SelectList(categories, "Id", "Name");
        return View();
    }


    //Add Post
    [HttpPost]
    public async Task<IActionResult> Add(ProductCreateDto productCreateDto)
    {
        var result = await _productService.Add(productCreateDto);
        if (!result.Success)
        {
            ModelState.AddModelError("errorMessage", result.Message);
            return View();
        }

        return RedirectToAction("Index");
    }


    // Update Get
    public async Task<IActionResult> Update(int id)
    {
        var categories = await _categoryService.GetAll();
        ViewData["categories"] = new SelectList(categories, "Id", "Name");

        var product = await _productService.Get(id);

        
        return View(product.Data);
    }


    //Update Post
    [HttpPost]
    public async Task<IActionResult> Update(ProductUpdateDto productUpdateDto)
    {
        var categories = await _categoryService.GetAll();
        ViewData["categories"] = new SelectList(categories, "Id", "Name");
        var result = await _productService.UpdateProduct(productUpdateDto);
        if (!result.Success)
        {
            ModelState.AddModelError("errorMessage", result.Message);
            return View();
        }

        return RedirectToAction("Index");
    }


    // Delete
    public async Task<IResult> Delete(int id)
    {
        return await _productService.Delete(id);
    }



    
    public async Task<IActionResult> ProductIndex()
    {
        var result = await _productService.ProductIndex();
        return View(result.Data);
    }
    
    
    
    
    public async Task<IActionResult> ProductDetail(int id)
    {
        
        var result = await _productService.ProductDetail(id);
        return View(result.Data);
    }
   



}

RepositoryDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RepositoryDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RepositoryDemo.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">Index</a>
            <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="ProductIndex">ProductIndex</a>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                    </li>
                    <li class="list-inline-item">
                        <a asp-controller="Account" asp-action="Register"><button class="btn-primary">Sign Up</button></a>
                    </li>
                    
                    <a asp-controller="Basket" asp-action="Index">
                        <span style="font-size: 20px">
                            <i class="fa-solid fa-basket-shopping"></i>
                            @* <span class="badge cbdg1" id="totalCountNav">@ViewBag.BasketCount</span> *@
                        </span>
                        @* <span class="cart-total position-relative" id="totalPriceNav"> @ViewBag.TotalPrice.ToString("C2")</span> *@
                    </a>
                    
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - RepositoryDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="https://kit.fontawesome.com/872796f0d8.js" crossorigin="anonymous"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>